// let users=[
//     {    
//        firsetName:"Hussam",
//        lastName:"Bawwab",
//        age:28,
//        address:"Irbid",
//        phoneNumber:"781586580",
//        jobDescription:{
//         title:"frontend",
//         salary:12332,
//   },
//   childreen:[
//     {
//         firsetName:"Samer",
//         lastName:"Bawwab",
//         age:3,
//     },
//     {
//         firsetName:"Bilal",
//         lastName:"Bawwab",
//         age:6,
//     },
//     {
//         firsetName:"Mariam",
//         lastName:"Bawwab",
//         age:8,
//     }
//   ]
// },
// {
    
//   firsetName:"Sara",
//   lastName:"Lobani",
//   age:22,
//   address:"Amman",
//   phoneNumber:"878455",
//   jobDescription:{
//         title:"frontend",
//         salary:184511,
//   },
//   childreen:[
//     {
//         firsetName:"Ali",
//         lastName:"LObani",
//         age:13,
//     },
//     {
//         firsetName:"Lobna",
//         lastName:"Lobani",
//         age:16,
//     },
//     {
//         firsetName:"Zaid",
//         lastName:"Lobani",
//         age:1,
//     }
//     ],
//   },
// {
//     firsetName:"abed",
//     lastName:"alsaad",
//     age:25,
//     address:"Amman",
//     phoneNumber:"74855",
//     jobDescription:{
//           title:"frontend",
//           salary:14111,
//     },
//     childreen:[
//       {
//           firsetName:"Rami",
//            astName:"Lobani",
//           age:20,
//       },
//       {
//           firsetName:"Omar",
//            astName:"Lobani",
//           age:9,
//       },
    
//     ],
//   },
//   {
//     firsetName:"Mohammad",
//     lastName:"Damra",
//     age:30,
//     address:"Amman",
//     phoneNumber:"7485555",
//     jobDescription:{
//           title:"frontend",
//           salary:1133,
//     },
//     childreen:[
//       {
//           firsetName:"Laith",
//            astName:"Damra",
//           age:1,
//       },
//       {
//           firsetName:"Ahmad",
//            astName:"Damra",
//           age:8,
//       },    
//     ],
//   },
// ];
// console.log(users.firsetName);